services:
  app:
    build: .
    volumes:
      - .:/app
      - ./audio_files:/app/audio_files
    env_file:
      - .env
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000')"]
      interval: 30s
      timeout: 10s
      retries: 3
